app:
  jwt:
    issuer: "dahada.com"
    secret: "dahadahadahadahadahadahadahadahadahadahadahadahadahadahadahadahadahadahadahadahadahadahadahadahadahadahada"
    token-policy:
      access-token-name: "access_token"
      access-token-life: 1h
      refresh-token-name: "refresh_token"
      refresh-token-life: 15d
  oauth2:
    registration:
      naver:
        client-id: ${naverClientId}
        client-secret: ${naverClientSecret}
        scope: name,email,profile_image
        redirect-uri: "http://localhost:8080/oauth/callback/naver"
        authorization-grant-type: authorization_code
        client-name: naver
        client-authentication-method: GET
        resource-url: "https://openapi.naver.com/v1/nid/me"
      kakao:
        client-id: ${kakaoClientId}
        client-secret: ${kakaoClientSecret}
        scope: profile,account_email
        redirect-uri: "http://localhost:8080/oauth/callback/kakao"
        authorization-grant-type: authorization_code
        client-name: kakao
        client-authentication-method: POST
        resource-url: "https://kapi.kakao.com/v2/user/me"

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    open-in-view: false

logging:
  level:
    com.dahada.backend: debug
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss:SSS} [%X{tracking} ++ %X{ipaddr}] [%thread] %-5level %logger{36} - %msg%n"
    console: "%(%d{yyyy-MM-dd HH:mm:ss:SSS} [%X{tracking} ++ %X{ipaddr}] [%thread] %-5level %logger{36} - %msg%n)"
  file:
    name: ./logs/dahada-dev.log
