spring:
  profiles:
    include: local-oauth
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    open-in-view: false
  oauth2:
    registration:
      naver:
        client-id: ${naverClientId}
        client-secret: ${naverClientSecret}
        scope: name,email,profile_image
        redirect-uri: "http://localhost:8080/oauth/callback/naver"
        authorization-grant-type: authorization_code
        client-name: naver
      kakao:
        client-id: ${kakaoClientId}
        client-secret: ${kakaoClientSecret}
        scope: profile,account_email
        redirect-uri: "http://localhost:8080/oauth/callback/kakao"
        authorization-grant-type: authorization_code
        client-name: kakao
        client-authentication-method: POST


logging:
  level:
    com.dahada.backend: debug
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss:SSS} [%X{tracking} ++ %X{ipaddr}] [%thread] %-5level %logger{36} - %msg%n"
    console: "%(%d{yyyy-MM-dd HH:mm:ss:SSS} [%X{tracking} ++ %X{ipaddr}] [%thread] %-5level %logger{36} - %msg%n)"
  file:
    name: ./logs/dahada-dev.log
